name: 'Deploy: Test'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy (Test)
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      ENVIRONMENT: staging
      BUCKET_DOMAIN_NAME: staging.yumdao.zone
