name: 'Deploy: Production'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy (production)
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      ENVIRONMENT: production
      BUCKET_DOMAIN_NAME: yumdao.zone
